### ISSUE TITLE
python3 setup.py test - Returned a Failure

### ISSUE THREAD

**Issue by simon-marriott** [dlitz/pycrypto#125]
python3 setup.py test - Returned a Failure:

Platform Ubuntu 14.04LTS in VirtualBox, running Python-3.4.2.
Here is what was reported (btw I am new to Python):-
simon@ubuntu-14:~$ cd pycrypto-2.6.1/
simon@ubuntu-14:~/pycrypto-2.6.1$ python3 setup.py test
running test
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SelfTest: You can ignore the RandomPool_DeprecationWarning that follows.
..........E...................
======================================================================
ERROR: test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ (Crypto.SelfTest.Util.test_number.MiscTests)
Test that mpzToLongObj and longObjToMPZ (internal functions) roundtrip negative numbers correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/lib.linux-x86_64-3.4/Crypto/SelfTest/Util/test_number.py", line 283, in test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ
    k = number._fastmath.rsa_construct(n, e)
AttributeError: 'NoneType' object has no attribute 'rsa_construct'

----------------------------------------------------------------------
Ran 1033 tests in 29.722s

FAILED (errors=1)
Traceback (most recent call last):
  File "setup.py", line 456, in <module>
    core.setup(**kw)
  File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 336, in run
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, config=self.config)
  File "build/lib.linux-x86_64-3.4/Crypto/SelfTest/__init__.py", line 74, in run
    raise SelfTestError("Self-test failed", result)
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestResult run=1033 errors=1 failures=0>)
simon@ubuntu-14:~/pycrypto-2.6.1$

**Comment by programingfrik** [comment]
(simon-marriot: put the output of the program in between "<pre></pre>" tags so its not interpreted as markdown)

I'm having the same problem, but I'm using Cygwin:
<pre>
PMercader@dti-6005-03 /cygdrive/d/comun/devz/win/python/pycrypto-2.6.1          
$ python3 setup.py test                                                         
running test                                                                    
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...........................................SelfTest: You can ignore the RandomPo
ol_DeprecationWarning that follows.                                             
..........E...................                                                  
======================================================================          
ERROR: test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ (Crypto.SelfTest
.Util.test_number.MiscTests)                                                    
Test that mpzToLongObj and longObjToMPZ (internal functions) roundtrip negative 
numbers correctly.                                                              
----------------------------------------------------------------------          
Traceback (most recent call last):                                              
  File "build/lib.cygwin-1.7.35-x86_64-3.2/Crypto/SelfTest/Util/test_number.py",
 line 283, in test_negative_number_roundtrip_mpzToLongObj_longObjToMPZ          
    k = number._fastmath.rsa_construct(n, e)                                    
AttributeError: 'NoneType' object has no attribute 'rsa_construct'              
                                                                                
----------------------------------------------------------------------          
Ran 1033 tests in 35.629s                                                       
                                                                                
FAILED (errors=1)                                                               
Traceback (most recent call last):                                              
  File "setup.py", line 456, in <module>                                        
    core.setup(**kw)                                                            
  File "/usr/lib/python3.2/distutils/core.py", line 148, in setup               
    dist.run_commands()                                                         
  File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands        
    self.run_command(cmd)                                                       
  File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command         
    cmd_obj.run()                                                               
  File "setup.py", line 336, in run                                             
    SelfTest.run(module=moduleObj, verbosity=self.verbose, stream=sys.stdout, co
nfig=self.config)                                                               
  File "build/lib.cygwin-1.7.35-x86_64-3.2/Crypto/SelfTest/__init__.py", line 74
, in run                                                                        
    raise SelfTestError("Self-test failed", result)                             
Crypto.SelfTest.SelfTestError: ('Self-test failed', <unittest.runner.TextTestRes
ult run=1033 errors=1 failures=0>)                                              
                                                                                
PMercader@dti-6005-03 /cygdrive/d/comun/devz/win/python/pycrypto-2.6.1          
$ cat README | less                                                             
                                                                                
PMercader@dti-6005-03 /cygdrive/d/comun/devz/win/python/pycrypto-2.6.1          
$ python3 --version                                                             
Python 3.2.5                                                                    
                                                                                
PMercader@dti-6005-03 /cygdrive/d/comun/devz/win/python/pycrypto-2.6.1          
$ uname -a                                                                      
CYGWIN_NT-6.3 dti-6005-03 1.7.35(0.287/5/3) 2015-03-04 12:09 x86_64 Cygwin      
                                                                                
PMercader@dti-6005-03 /cygdrive/d/comun/devz/win/python/pycrypto-2.6.1          
$                                                                               
</pre>

**Comment by TiTi87** [comment]
Hello, 
I had the same issue this morning 
after a closer look, an error did appears that during the build : 
<pre>~/pycrypto # python setup.py build
[...]
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.</pre>

I resolved this error by installing the MIPR lib as follow :

<pre>wget http://mpir.org/mpir-2.7.2.tar.bz2
tar -xvf mpir-2.7.2.tar.bz2 mpir-2.7.2/
cd mpir-2.7.2/
./configure --enable-gmpcompat 
make
make check
make install
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"</pre>

and then rebuilding and install pycrypto
<pre>python setup.py build
python setup.py install
python setup.py test
</pre>

Hope it helps.
