### ISSUE TITLE
pycrypto 2.7a1 missing Crypto.Hash SHA256

### ISSUE THREAD

**Issue by tektengu** [dlitz/pycrypto#140]
I manually included the library component of the pycrypto 2.7a1 into my project and now it is missing the SHA256 has. Looking in the directory and .py files there is no SHA256. Here is the stack trace from PyCharm in building this.

Traceback (most recent call last):
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/restler.py", line 8, in <module>
    from Crypto.PublicKey import RSA
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/PublicKey/RSA.py", line 79, in <module>
    from Crypto.IO import PKCS8, PEM
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/IO/PKCS8.py", line 57, in <module>
    from Crypto.IO._PBES import PBES1, PBES2
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/IO/_PBES.py", line 27, in <module>
    from Crypto import Random
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/Random/Fortuna/FortunaAccumulator.py", line 37, in <module>
    import SHAd256
  File "/Users/mindninja/Documents/Working/labs/projects/python/auth-restler/Crypto/Random/Fortuna/SHAd256.py", line 41, in <module>
    from Crypto.Hash import SHA256
ImportError: cannot import name SHA256

**Comment by lafrank** [comment]
Any update on this please ? I am also facing with this issue.

**Comment by mouse07410** [comment]
The update/answer is [pycryptodome](http://pycryptodome.readthedocs.io/en/latest/)

The alternative is to keep suffering

**Comment by mikez302** [comment]
I don't think this project is being maintained any more. For more info, see https://github.com/dlitz/pycrypto/issues/173.

**Comment by lafrank** [comment]
Thanks, this was my impression also :-(
