### ISSUE TITLE
Build fails if 'configure' is elsewhere in your path

### ISSUE THREAD

**Issue by bennoleslie** [dlitz/pycrypto#154]
The build fails with the following:

```
configure: error: cannot find sources (src/pycrypto_compat.h) in /Users/benno/local/src/wine-master or ..
Traceback (most recent call last):
  File "setup.py", line 510, in <module>
    core.setup(**kw)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 256, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 315, in run
    raise RuntimeError("autoconf error")
RuntimeError: autoconf error
```

If you happen to have a file called **configure** elsewhere in your path.

Calling "./configure" and then doing the build is one workaround. (As is removing the other directory from your path that happens to have configure in it).

The problematic code is in the configure script itself:

```
# IFS
# We need space, tab and new line, in precisely that order.  Quoting is
# there to prevent editors from complaining about space-tab.
# (If _AS_PATH_WALK were called with IFS unset, it would disable word
# splitting by setting IFS to empty value.)
IFS=" ""	$as_nl"

# Find who we are.  Look in the path if we contain no directory separator.
as_myself=
case $0 in #((
  *[\\/]* ) as_myself=$0 ;;
  *) as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
for as_dir in $PATH
do
  IFS=$as_save_IFS
  test -z "$as_dir" && as_dir=.
    test -r "$as_dir/$0" && as_myself=$as_dir/$0 && break
  done
IFS=$as_save_IFS

     ;;
esac
```

If $0 (i.e.: the current executable) doesn't have a **/** or **\** in it, then it searches the path until it finds a directory that does have configure in it. Unfortunately that is just a plain wrong approach to determining the location of the current executable.

I'm sure this code is inherited from autoconf somewhere, so the problem is probably way upstream, and there is little incentive to fix it. Changing the code in setup.py to "sh ./configure" fixes this problem, but may break on windows(?).

**Comment by wbrefvem** [comment]
> that is just a plain wrong approach to determining the location of the current executable  

I couldn't agree more. I had [pfff](https://github.com/facebook/pfff/) installed, and at some point (whether in a fit of insanity or while following instructions--I can't remember which) I added pfff's top level dir to my PATH, which just happens to have a--wait for it--configure script. Putting a configure script on your PATH is bad. Expecting one to be there is worse. @bennoleslie if I could gild your comment, I would.
