### ISSUE TITLE
pip install places pycrypto in lowercase 'crypto' on windows.

### ISSUE THREAD

**Issue by Grazfather** [dlitz/pycrypto#156]
Windows XP SP4, Python 2.7

`python -m pip install pycrypto` succeeds after installing the compiler, but it fails to load:

```
>>> from Crypto.Cipher import AES
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Crypto.Cipher
>>> from crypto.Cipher import AES
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\crypto\Cipher\AES.py", line 49, in <module
>
    from Crypto.Cipher import blockalgo
ImportError: No module named Crypto.Cipher
```

Notice 'crypto' in site-packages is lowercase? Renaming it to 'Crypto' seems to solve the issue.

**Comment by alawal123** [comment]
From the look of things the  pycrypto module is not installed on your system. Try this 

https://luiscberrocal.wordpress.com/2012/07/18/installing-and-using-pycrypto-on-windows-7/

**Comment by Grazfather** [comment]
No, it is installed. I verified it exists in site-packages, and like I said, renaming _crypto_ to _Crypto_ solved the issue.

I actually think the issue is the following:

1. I ran `pip install crypto` (Creates 'crypto' in site-packages)
2. I ran `pip install pycrypto` (Puts pycrypto in lowercase crypto, since the directory already exists)
3. I tried to `import Crypto`. This failed because presumably pythons `__import__` checks directories in a case-sensitive way.

I can verify tonight if this is the case. If so, then I think it's a `pip` issue.

**Comment by jomido** [comment]
This just occurred to me today. Thanks for posting your solution.

**Comment by amremam2004** [comment]
under lib/site-packages rename crypto folder to Crypto

**Comment by mike-bailey** [comment]
Can confirm, this is a bug.

**Comment by thecodingchicken** [comment]
This is a bug.  It is only imported as 'crypto', but it is imported as Crypto in the library's files.

**Comment by darouwan** [comment]
I ever submitted this issue before, but it was closed by someone...

**Comment by mike-bailey** [comment]
Sounds like this project is dead

**Comment by darouwan** [comment]
@mike-bailey yep , the latest release was on four years ago

**Comment by askerlee** [comment]
You can use pycryptodome, which is a fork of pycrypto and is actively developed. However the same problem exists with this package. Renaming works 😄

**Comment by lemenkov** [comment]
Dupe of #285

**Comment by Mike-Logit** [comment]
This has been a real problem for us and very happy to have found this git issue. Any bug fix ETA?

**Comment by avrajsri** [comment]
pip uninstall crypto
Delete "crypto" Folder [C:\Users\AppData\Local\Programs\Python\Python37\Lib\site-packages]
pip install crypto
pip uninstall pycryptodome
pip install pycryptodome

Rename Folder "crypto" to "Crypto" [C:\Users\AppData\Local\Programs\Python\Python37\Lib\site-packages]

Then You Use "from Crypto.Cipher import AES" in Code

**Comment by tina0430** [comment]
Thank you, @avrajsri
I solved my issue!

**Comment by clintonb** [comment]
This is an issue on macOS, too, which may also be case-insensitive.
