### ISSUE TITLE
I get an error when installing PyCrypto with Python 3.5

### ISSUE THREAD

**Issue by jcea** [dlitz/pycrypto#168]
The compilation and installation succeed, but there is an ugly error during the process:

```
  running install_egg_info
  running egg_info
  creating pycrypto.egg-info
  writing dependency_links to pycrypto.egg-info/dependency_links.txt
  writing top-level names to pycrypto.egg-info/top_level.txt
  writing pycrypto.egg-info/PKG-INFO
  writing manifest file 'pycrypto.egg-info/SOURCES.txt'
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'pycrypto.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pycrypto.egg-info/SOURCES.txt'
  Copying pycrypto.egg-info to build/bdist.linux-x86_64/wheel/pycrypto-2.6.1-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vk3e3zoq/pycrypto/setup.py", line 456, in <module>
      core.setup(**kw)
    File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/openbadges/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/tmp/openbadges/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/tmp/openbadges/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for pycrypto
Failed to build pycrypto
Installing collected packages: pycrypto
  Found existing installation: pycrypto 2.6.1
    Uninstalling pycrypto-2.6.1:
      Successfully uninstalled pycrypto-2.6.1
  Running setup.py install for pycrypto
Successfully installed pycrypto-2.6.1
```

The resulting install works correctly, but that error is confusing and leads to believe that installations is in bad shape.

**Comment by johnthagen** [comment]
And I get the following install error when installing on Python 3.5.0 (on Windows 10):

```
C:\Users\John Hagen>pip install pycrypto
Collecting pycrypto
  Using cached pycrypto-2.6.1.tar.gz
Installing collected packages: pycrypto
  Running setup.py install for pycrypto
    Complete output from command "c:\users\john hagen\appdata\local\programs\python\python35-32\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\JOHNHA~1\\AppData\\Local\\Temp\\pip-build-qlqzu2nw\\pycrypto\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\JOHNHA~1\AppData\Local\Temp\pip-qtx80_my-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\Crypto
    copying lib\Crypto\pct_warnings.py -> build\lib.win32-3.5\Crypto
    copying lib\Crypto\__init__.py -> build\lib.win32-3.5\Crypto
    creating build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\hashalgo.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\HMAC.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\MD2.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\MD4.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\MD5.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\RIPEMD.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\SHA.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\SHA224.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\SHA256.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\SHA384.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\SHA512.py -> build\lib.win32-3.5\Crypto\Hash
    copying lib\Crypto\Hash\__init__.py -> build\lib.win32-3.5\Crypto\Hash
    creating build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\AES.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\ARC2.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\ARC4.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\blockalgo.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\Blowfish.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\CAST.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\DES.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\DES3.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\PKCS1_OAEP.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\PKCS1_v1_5.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\XOR.py -> build\lib.win32-3.5\Crypto\Cipher
    copying lib\Crypto\Cipher\__init__.py -> build\lib.win32-3.5\Crypto\Cipher
    creating build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\asn1.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\Counter.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\number.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\py3compat.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\randpool.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\RFC1751.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\winrandom.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\_number_new.py -> build\lib.win32-3.5\Crypto\Util
    copying lib\Crypto\Util\__init__.py -> build\lib.win32-3.5\Crypto\Util
    creating build\lib.win32-3.5\Crypto\Random
    copying lib\Crypto\Random\random.py -> build\lib.win32-3.5\Crypto\Random
    copying lib\Crypto\Random\_UserFriendlyRNG.py -> build\lib.win32-3.5\Crypto\Random
    copying lib\Crypto\Random\__init__.py -> build\lib.win32-3.5\Crypto\Random
    creating build\lib.win32-3.5\Crypto\Random\Fortuna
    copying lib\Crypto\Random\Fortuna\FortunaAccumulator.py -> build\lib.win32-3.5\Crypto\Random\Fortuna
    copying lib\Crypto\Random\Fortuna\FortunaGenerator.py -> build\lib.win32-3.5\Crypto\Random\Fortuna
    copying lib\Crypto\Random\Fortuna\SHAd256.py -> build\lib.win32-3.5\Crypto\Random\Fortuna
    copying lib\Crypto\Random\Fortuna\__init__.py -> build\lib.win32-3.5\Crypto\Random\Fortuna
    creating build\lib.win32-3.5\Crypto\Random\OSRNG
    copying lib\Crypto\Random\OSRNG\fallback.py -> build\lib.win32-3.5\Crypto\Random\OSRNG
    copying lib\Crypto\Random\OSRNG\nt.py -> build\lib.win32-3.5\Crypto\Random\OSRNG
    copying lib\Crypto\Random\OSRNG\posix.py -> build\lib.win32-3.5\Crypto\Random\OSRNG
    copying lib\Crypto\Random\OSRNG\rng_base.py -> build\lib.win32-3.5\Crypto\Random\OSRNG
    copying lib\Crypto\Random\OSRNG\__init__.py -> build\lib.win32-3.5\Crypto\Random\OSRNG
    creating build\lib.win32-3.5\Crypto\SelfTest
    copying lib\Crypto\SelfTest\st_common.py -> build\lib.win32-3.5\Crypto\SelfTest
    copying lib\Crypto\SelfTest\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest
    creating build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\common.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_AES.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_ARC2.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_ARC4.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_Blowfish.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_CAST.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_DES.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_DES3.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_pkcs1_15.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_pkcs1_oaep.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\test_XOR.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    copying lib\Crypto\SelfTest\Cipher\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Cipher
    creating build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\common.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_HMAC.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_MD2.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_MD4.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_MD5.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_RIPEMD.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_SHA.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_SHA224.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_SHA256.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_SHA384.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\test_SHA512.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    copying lib\Crypto\SelfTest\Hash\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Hash
    creating build\lib.win32-3.5\Crypto\SelfTest\Protocol
    copying lib\Crypto\SelfTest\Protocol\test_AllOrNothing.py -> build\lib.win32-3.5\Crypto\SelfTest\Protocol
    copying lib\Crypto\SelfTest\Protocol\test_chaffing.py -> build\lib.win32-3.5\Crypto\SelfTest\Protocol
    copying lib\Crypto\SelfTest\Protocol\test_KDF.py -> build\lib.win32-3.5\Crypto\SelfTest\Protocol
    copying lib\Crypto\SelfTest\Protocol\test_rfc1751.py -> build\lib.win32-3.5\Crypto\SelfTest\Protocol
    copying lib\Crypto\SelfTest\Protocol\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Protocol
    creating build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    copying lib\Crypto\SelfTest\PublicKey\test_DSA.py -> build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    copying lib\Crypto\SelfTest\PublicKey\test_ElGamal.py -> build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    copying lib\Crypto\SelfTest\PublicKey\test_importKey.py -> build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    copying lib\Crypto\SelfTest\PublicKey\test_RSA.py -> build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    copying lib\Crypto\SelfTest\PublicKey\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\PublicKey
    creating build\lib.win32-3.5\Crypto\SelfTest\Random
    copying lib\Crypto\SelfTest\Random\test_random.py -> build\lib.win32-3.5\Crypto\SelfTest\Random
    copying lib\Crypto\SelfTest\Random\test_rpoolcompat.py -> build\lib.win32-3.5\Crypto\SelfTest\Random
    copying lib\Crypto\SelfTest\Random\test__UserFriendlyRNG.py -> build\lib.win32-3.5\Crypto\SelfTest\Random
    copying lib\Crypto\SelfTest\Random\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Random
    creating build\lib.win32-3.5\Crypto\SelfTest\Random\Fortuna
    copying lib\Crypto\SelfTest\Random\Fortuna\test_FortunaAccumulator.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\Fortuna
    copying lib\Crypto\SelfTest\Random\Fortuna\test_FortunaGenerator.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\Fortuna
    copying lib\Crypto\SelfTest\Random\Fortuna\test_SHAd256.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\Fortuna
    copying lib\Crypto\SelfTest\Random\Fortuna\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\Fortuna
    creating build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\test_fallback.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\test_generic.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\test_nt.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\test_posix.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\test_winrandom.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    copying lib\Crypto\SelfTest\Random\OSRNG\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Random\OSRNG
    creating build\lib.win32-3.5\Crypto\SelfTest\Util
    copying lib\Crypto\SelfTest\Util\test_asn1.py -> build\lib.win32-3.5\Crypto\SelfTest\Util
    copying lib\Crypto\SelfTest\Util\test_Counter.py -> build\lib.win32-3.5\Crypto\SelfTest\Util
    copying lib\Crypto\SelfTest\Util\test_number.py -> build\lib.win32-3.5\Crypto\SelfTest\Util
    copying lib\Crypto\SelfTest\Util\test_winrandom.py -> build\lib.win32-3.5\Crypto\SelfTest\Util
    copying lib\Crypto\SelfTest\Util\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Util
    creating build\lib.win32-3.5\Crypto\SelfTest\Signature
    copying lib\Crypto\SelfTest\Signature\test_pkcs1_15.py -> build\lib.win32-3.5\Crypto\SelfTest\Signature
    copying lib\Crypto\SelfTest\Signature\test_pkcs1_pss.py -> build\lib.win32-3.5\Crypto\SelfTest\Signature
    copying lib\Crypto\SelfTest\Signature\__init__.py -> build\lib.win32-3.5\Crypto\SelfTest\Signature
    creating build\lib.win32-3.5\Crypto\Protocol
    copying lib\Crypto\Protocol\AllOrNothing.py -> build\lib.win32-3.5\Crypto\Protocol
    copying lib\Crypto\Protocol\Chaffing.py -> build\lib.win32-3.5\Crypto\Protocol
    copying lib\Crypto\Protocol\KDF.py -> build\lib.win32-3.5\Crypto\Protocol
    copying lib\Crypto\Protocol\__init__.py -> build\lib.win32-3.5\Crypto\Protocol
    creating build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\DSA.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\ElGamal.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\pubkey.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\RSA.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\_DSA.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\_RSA.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\_slowmath.py -> build\lib.win32-3.5\Crypto\PublicKey
    copying lib\Crypto\PublicKey\__init__.py -> build\lib.win32-3.5\Crypto\PublicKey
    creating build\lib.win32-3.5\Crypto\Signature
    copying lib\Crypto\Signature\PKCS1_PSS.py -> build\lib.win32-3.5\Crypto\Signature
    copying lib\Crypto\Signature\PKCS1_v1_5.py -> build\lib.win32-3.5\Crypto\Signature
    copying lib\Crypto\Signature\__init__.py -> build\lib.win32-3.5\Crypto\Signature
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'Crypto.Random.OSRNG.winrandom' extension
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command ""c:\users\john hagen\appdata\local\programs\python\python35-32\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\JOHNHA~1\\AppData\\Local\\Temp\\pip-build-qlqzu2nw\\pycrypto\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\JOHNHA~1\AppData\Local\Temp\pip-qtx80_my-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\JOHNHA~1\AppData\Local\Temp\pip-build-qlqzu2nw\pycrypto
```
Seems to be more justification for #137.

**Comment by mertz3hack** [comment]
How do you get around that error?
 building 'Crypto.Random.OSRNG.winrandom' extension
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

**Comment by johnthagen** [comment]
@mertz3hack My solution was to switch to [cryptography](https://pypi.python.org/pypi/cryptography) or [pycryptodome](https://pypi.python.org/pypi/pycryptodome) which both provide official wheels for Windows.

My understanding is that `pycrypto` is no longer maintained.

**Comment by mertz3hack** [comment]
@johnthagen Thanks I will give that a try!

**Comment by maangulo12** [comment]
Yup. Experienced the same problem.

**Comment by innovasolutionsdatascience** [comment]
go
