### ISSUE TITLE
problem generating random numbers with pypy3

### ISSUE THREAD

**Issue by nlitsme** [dlitz/pycrypto#214]
this simple program fails when executed with pypy3:

    import Crypto.Util.number
    Crypto.Util.number.getRandomNBitInteger(16)

The error is: `TypeError: argument 1 must be contiguous buffer, not bytes`.

The problem seems to be that _AES thinks the bytes argument for the key is not contiguous, while in fact it is.
Maybe it is to do with the argument check in the call to `PyArg_ParseTupleAndKeywords` in block_template.c?

the full error message:

    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Util/number.py", line 138, in getRandomNBitInteger
        value = getRandomInteger (N-1, randfunc)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Util/number.py", line 104, in getRandomInteger
        S = randfunc(N>>3)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
        return self._singleton.read(bytes)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
        return _UserFriendlyRNG.read(self, bytes)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 132, in read
        retval = self._fa.random_data(N)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 146, in random_data
        self._reseed(current_time)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 161, in _reseed
        self.generator.reseed(seed)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 82, in reseed
        self._set_key(SHAd256.new(self.key + seed).digest())
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 101, in _set_key
        self._cipher = AES.new(key, AES.MODE_CTR, counter=self.counter)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Cipher/AES.py", line 95, in new
        return AESCipher(key, *args, **kwargs)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
        blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
      File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
        self._cipher = factory.new(key, *args, **kwargs)
    TypeError: argument 1 must be contiguous buffer, not bytes

**Comment by flniu** [comment]
I met same issue with pypy3 5.5.0 and pycrypto 2.6.1:
```
Python 3.3.5 (ea9979b550eeae87924dc4bef06070e8f8d0e22f, Nov 25 2016, 07:04:09)
[PyPy 5.5.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from Crypto.Cipher import AES
>>>> key = b'1' * 16
>>>> type(key)
<class 'bytes'>
>>>> AES.new(key, AES.MODE_ECB)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/admin/.virtualenvs/pypy-lms/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/Users/admin/.virtualenvs/pypy-lms/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/Users/admin/.virtualenvs/pypy-lms/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
TypeError: argument 1 must be contiguous buffer, not bytes
```

**Comment by Varbin** [comment]
Please see #238.
