### ISSUE TITLE
AttributeError: function/symbol 'SHA256_init' not found in library

### ISSUE THREAD

**Issue by yamadakinya** [dlitz/pycrypto#233]
pycrypto 2.6 SHA256 run unit  test show below error message
would some figure out what is the problem?
OS:
Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F2073)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: YamadaのiMac
      User Name: Yamada (yamada)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 55 minutes

Python:
Python 2.7.13

$ python test_SHA256.py 
EEEEEEEE
======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #1: 'abc'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #2: 'abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #3: "a" * 10**6
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #4: Length = 55 (mod 64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #5: ''
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashSelfTest)
SHA256 #6: 'Franz jagt im komplett verwahrlosten Taxi quer durch Bayern'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 76, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashDigestSizeSelfTest)
SHA256 #6: digest_size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 58, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

======================================================================
ERROR: runTest (common.HashTestOID)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yamada/Downloads/pycrypto-2.6.1/lib/Crypto/SelfTest/Hash/common.py", line 110, in runTest
    h = self.hashmod.new()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 166, in new
    return SHA256Hash().new(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Hash/SHA256.py", line 70, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 866, in __getattr__
    make_accessor(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 862, in make_accessor
    accessors[name](name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 792, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Crypto/Util/../Hash/_SHA256.so': dlsym(0x102a36020, SHA256_init): symbol not found

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (errors=8)

**Comment by Varbin** [comment]
1. Format your bug report.
2. Please see #238.

**Comment by StevenLWill** [comment]
I ran into the same error, but on Windows, and with Python 3.7, and when trying to use the Web3 module; Since there doesn't seem to be much information out there about this particular error, I thought I'd throw my solution out there. I ended up running the below commands:
```
pip uninstall pycryptodome
pip install pycryptodome==3.5
```

**Comment by AlexEBall** [comment]
I also ran into this error and in my virtualenv I had also installed the package `pycrypto`

However on [pycryptodome's github](https://github.com/Legrandin/pycryptodome) they mention you shouldn't have `pycrypto` and `pycryptodome` installed at the same time as they will interfere with each other

So it wasn't until I uninstalled `pycrypto` and then installed `pycryptodome` that this error went away. For what it's worth, I installed `pycryptodome==3.10.1` and had no problem. My venv is running Python 3.8 on Mac Catalina
