### ISSUE TITLE
'RsaKey' object has no attribute '_randfunc'

### ISSUE THREAD

**Issue by whaoming** [dlitz/pycrypto#235]
hello,I got a problem:

python -v:3.6
pycrypto :version:2.6.1

code:
    def rsa_base64_encrypt(data):
        """rsa_base64_encrypt"""
        content = open('rsa_public_key.pem').read()
        cipher = PKCS1_v1_5.new(RSA.import_key(content))
        return base64.b64encode(cipher.encrypt(bytes(data, encoding="utf8")))

the key is mke by openssl

exception:
Traceback (most recent call last):
  File "/Users/squirrel/Desktop/pro_py/BicycleServer_python/DecodeFilter.py", line 28, in <module>
    dataa = MerchantAPI.rsa_base64_encrypt('asdasd')
  File "/Users/squirrel/Desktop/pro_py/BicycleServer_python/DecodeFilter.py", line 24, in rsa_base64_encrypt
    return base64.b64encode(cipher.encrypt(bytes(data, encoding="utf8")))
  File "/Users/squirrel/tornado-env/lib/python3.6/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 119, in encrypt
    randFunc = self._key._randfunc
AttributeError: 'RsaKey' object has no attribute '_randfunc'

Can you tell me how it was done,thanks

**Comment by Varbin** [comment]
Please see #238.
