### ISSUE TITLE
Encrypting content in python 3 is a BUG in Chinese

### ISSUE THREAD

**Issue by 154247575** [dlitz/pycrypto#242]
Let's look at this situation first
```
>>> txt = '啊啊啊啊啊1'
#python2
>>> len(txt)
16
#python3
>>> len(txt)
6
```

The following are python3

The first example
```
>>> txt = '123456789啊123456'
>>> len(txt)
16
>>> from Crypto.Cipher import AES
>>> obj = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> ciphertext = obj.encrypt(txt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
ValueError: Input strings must be a multiple of 16 in length
```

#Second example
```
#Look at the previous note.
#I judgment that python2 is still in use in the pycrypto module
>>> txt = '啊啊啊啊啊1'
>>> len(txt)
6
>>> from Crypto.Cipher import AES
>>> obj = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> ciphertext = obj.encrypt(txt)
>>> ciphertext
b"\xb2c\xec\xe8\xdbN\xe5J_>1a\xf5\x1b\x81\x97\x85N\xc1[\x92\x9b)p\x7f&<.wA\x83\xedW\xcdj\x1a<\x8f*\xbdF_\x97E'1r\xa1"
>>> obj2 = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> obj2.decrypt(ciphertext)
b' \xc1\xd0+\x00\xc5\xa9%\xd5\xfb\xaa\xa3\xc2\xfc\xd6\x91\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a'

```

#The third example
```
#I'm starting to get a little confused
>>> txt = '啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊'
>>> len(txt)
16
>>> from Crypto.Cipher import AES
>>> obj = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> ciphertext = obj.encrypt(txt)
>>> ciphertext
b"$\xb4\xa2\xdf\xb7<rdmg\xb6\xbd0|L\xd9\x83\xf6@\xddp\xe3\x92\xc7\xdc\xdd\xc2s\x89\xbcf\xcbM\xac&\xb4\xdc\x9f\xdcxQN\x88\x1eyp'\xe5"
>>> obj2 = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> obj2.decrypt(ciphertext)
b'\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a\xe5\x95\x8a'
```

#The normal results
```
#Pure Numbers or English characters are normal
>>> txt = '123456789a123456'
>>> 
>>> from Crypto.Cipher import AES
>>> obj = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> ciphertext = obj.encrypt(txt)
>>> ciphertext
b'\xd8e\xa9B!\xabBk<\x19\x9fO\x93 6\xf4'
>>> obj2 = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
>>> obj2.decrypt(ciphertext)
b'123456789a123456'

```

**Comment by AraHaan** [comment]
Take a look at #238.
