### ISSUE TITLE
python2.7.10, cannot import name winrandom

### ISSUE THREAD

**Issue by ghwyyx** [dlitz/pycrypto#261]
Traceback (most recent call last):
  File "vtest.py", line 6, in <module>
    from Crypto.PublicKey import RSA
  File "C:\Python27\lib\Crypto\PublicKey\RSA.py", line 79, in <module>
    from Crypto.IO import PKCS8, PEM
  File "C:\Python27\lib\Crypto\IO\PKCS8.py", line 57, in <module>
    from Crypto.IO._PBES import PBES1, PBES2
  File "C:\Python27\lib\Crypto\IO\_PBES.py", line 27, in <module>
    from Crypto import Random
  File "C:\Python27\lib\Crypto\Random\__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "C:\Python27\lib\Crypto\Random\OSRNG\__init__.py", line 34, in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\Python27\lib\Crypto\Random\OSRNG\nt.py", line 28, in <module>
    from Crypto.Random.OSRNG import winrandom
ImportError: cannot import name winrandom

**Comment by martin-weismann** [comment]
Just had the same issue.
If you can, switch to pycryptodome: https://github.com/dlitz/pycrypto/issues/238

**Comment by MatthewScholefield** [comment]
Yep, PyCrypto is essentially dead (#238). Try using [PyCryptodome](https://github.com/Legrandin/pycryptodome) instead.

**Comment by Deerajreddy9** [comment]
Problem is solved by editing string in **crypto\Random\OSRNG\nt.py**:

`import winrandom`  or `from Crypto.Random.OSRNG import winrandom`
to

`from . import winrandom`
