### ISSUE TITLE
Encoding issue with hashing

### ISSUE THREAD

**Issue by Patrick-DS** [dlitz/pycrypto#262]
When I try to run the following example code 

>>> from Crypto.Hash import SHA256
>>> hash = SHA256.new()
>>> hash.update('message')

I get the error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/hashalgo.py", line 69, in update
    return self._hash.update(data)
TypeError: Unicode-objects must be encoded before hashing

. Has anything changed between the Python versions and the versions of this code? I manage to hash by replacing hash.update('message') by hash.update('message'.encode()) but this is not the only place where I encounter problems ; I get errors I don't really understand when using the AES function, so perhaps clearing this error up will tell me how to describe the other errors I get.

**Comment by MatthewScholefield** [comment]
PyCrypto is essentially dead (#238). Try using [PyCryptodome](https://github.com/Legrandin/pycryptodome) instead.
