### ISSUE TITLE
time.clock() is deprecated as of 3.8+

### ISSUE THREAD

**Issue by xradiation** [dlitz/pycrypto#304]
>>>rsaKey = RSA.generate(1024, RNG)

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/PublicKey/RSA.py", line 508, in generate
    obj = _RSA.generate_py(bits, rf, progress_func, e)    # TODO: Don't use legacy _RSA module
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/PublicKey/_RSA.py", line 50, in generate_py
    p = pubkey.getStrongPrime(bits>>1, obj.e, 1e-12, randfunc)
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Util/number.py", line 264, in getStrongPrime
    return _fastmath.getStrongPrime(int(N), int(e), false_positive_prob,
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/home/usre/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
AttributeError: module 'time' has no attribute 'clock'
`

**using time.time() is supposed to fix the issue.**
edit : replacing time.clock() in `/home/user/.local/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py` with time.time() or time.process_time() is not enough to fix the issue.

**Comment by xradiation** [comment]
migration from `pycrypto` to `pycryptodome` (pycrypto fork) is possible solution.

**Comment by vishva8kumara** [comment]
I have this fix for this:
`diff --git a/lib/Crypto/Random/_UserFriendlyRNG.py b/lib/Crypto/Random/_UserFriendlyRNG.py
index 957e006..d2a0259 100644
--- a/lib/Crypto/Random/_UserFriendlyRNG.py
+++ b/lib/Crypto/Random/_UserFriendlyRNG.py
@@ -74,7 +74,7 @@ class _EntropyCollector(object):
         self._time_es.feed(struct.pack("@I", int(2**30 * (t - floor(t)))))
 
         # Add the fractional part of time.clock()
-        t = time.clock()
+        t = time.process_time()
         self._clock_es.feed(struct.pack("@I", int(2**30 * (t - floor(t)))))
`
